# Generated by Django 2.0 on 2019-12-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtype',
            old_name='blogtype',
            new_name='type_name',
        ),
    ]
